"""autogen: CK Part.CurrentStock>=0

Revision ID: 18152ba27da7
Revises: cdb727ea3420
Create Date: 2025-08-26 11:18:10.763867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18152ba27da7'
down_revision: Union[str, Sequence[str], None] = 'cdb727ea3420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
