"""add AppUser

Revision ID: 1b6cd5d07169
Revises: b86dd912615f
Create Date: 2025-08-25 11:58:42.363290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b6cd5d07169'
down_revision: Union[str, Sequence[str], None] = 'b86dd912615f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AppUser',
    sa.Column('UserID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Username', sa.String(length=50), nullable=False),
    sa.Column('FullName', sa.String(length=100), nullable=True),
    sa.Column('Email', sa.String(length=200), nullable=True),
    sa.Column('HashedPassword', sa.String(length=255), nullable=False),
    sa.Column('Role', sa.String(length=20), server_default='viewer', nullable=False),
    sa.Column('IsActive', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('SYSDATETIME()'), nullable=False),
    sa.CheckConstraint("Role in ('viewer','operator','tech','store','admin')", name='CK_AppUser_Role'),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AppUser')
    # ### end Alembic commands ###
