"""check WorkOrder unique

Revision ID: 961e99eab619
Revises: f70d5b9e52d1
Create Date: 2025-09-21 16:44:33.640378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '961e99eab619'
down_revision: Union[str, Sequence[str], None] = 'f70d5b9e52d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Machine', 'Name',
               existing_type=sa.NVARCHAR(length=255, collation='Turkish_CI_AS'),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('Machine', 'Location',
               existing_type=sa.NVARCHAR(length=255, collation='Turkish_CI_AS'),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Part', 'PartName',
               existing_type=sa.NVARCHAR(length=255, collation='Turkish_CI_AS'),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.drop_index(op.f('IX_PurchaseOrder_PODate'), table_name='PurchaseOrder')
    op.drop_index(op.f('IX_PurchaseOrder_PartID'), table_name='PurchaseOrder')
    op.drop_index(op.f('IX_PurchaseOrder_Status'), table_name='PurchaseOrder')
    op.drop_index(op.f('IX_PurchaseOrder_Status_PODate'), table_name='PurchaseOrder')
    op.drop_index(op.f('IX_PurchaseOrder_SupplierID'), table_name='PurchaseOrder')
    op.alter_column('Supplier', 'Phone',
               existing_type=sa.VARCHAR(length=20, collation='Turkish_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('Technician', 'FullName',
               existing_type=sa.VARCHAR(length=100, collation='Turkish_CI_AS'),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('Technician', 'SkillLevel',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('Technician', 'Phone',
               existing_type=sa.VARCHAR(length=15, collation='Turkish_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('WarehouseTxn', 'Reason',
               existing_type=sa.NVARCHAR(length=255, collation='Turkish_CI_AS'),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index(op.f('IX_WarehouseTxn_PartID'), table_name='WarehouseTxn')
    op.alter_column('WorkOrder', 'Notes',
               existing_type=sa.NVARCHAR(collation='Turkish_CI_AS'),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_index(op.f('IX_WorkOrder_Active_ByStatus'), table_name='WorkOrder', mssql_where="([Status_s] IN ('Open', 'InProgress'))", mssql_include=['RequestID', 'TechnicianID'])
    op.drop_index(op.f('IX_WorkOrder_Active_ByTech'), table_name='WorkOrder', mssql_where="([Status_s] IN ('Open', 'InProgress'))", mssql_include=['RequestID', 'Status_s'])
    op.drop_index(op.f('IX_WorkOrder_Tech_History'), table_name='WorkOrder', mssql_include=['RequestID', 'Status_s'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('IX_WorkOrder_Tech_History'), 'WorkOrder', ['TechnicianID', 'OpenedAt'], unique=False, mssql_include=['RequestID', 'Status_s'])
    op.create_index(op.f('IX_WorkOrder_Active_ByTech'), 'WorkOrder', ['TechnicianID', 'OpenedAt'], unique=False, mssql_where="([Status_s] IN ('Open', 'InProgress'))", mssql_include=['RequestID', 'Status_s'])
    op.create_index(op.f('IX_WorkOrder_Active_ByStatus'), 'WorkOrder', ['Status_s', 'OpenedAt'], unique=False, mssql_where="([Status_s] IN ('Open', 'InProgress'))", mssql_include=['RequestID', 'TechnicianID'])
    op.alter_column('WorkOrder', 'Notes',
               existing_type=sa.String(length=1000),
               type_=sa.NVARCHAR(collation='Turkish_CI_AS'),
               existing_nullable=True)
    op.create_index(op.f('IX_WarehouseTxn_PartID'), 'WarehouseTxn', ['PartID'], unique=False)
    op.alter_column('WarehouseTxn', 'Reason',
               existing_type=sa.String(length=100),
               type_=sa.NVARCHAR(length=255, collation='Turkish_CI_AS'),
               existing_nullable=True)
    op.alter_column('Technician', 'Phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=15, collation='Turkish_CI_AS'),
               existing_nullable=True)
    op.alter_column('Technician', 'SkillLevel',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('Technician', 'FullName',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100, collation='Turkish_CI_AS'),
               existing_nullable=False)
    op.alter_column('Supplier', 'Phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20, collation='Turkish_CI_AS'),
               existing_nullable=True)
    op.create_index(op.f('IX_PurchaseOrder_SupplierID'), 'PurchaseOrder', ['SupplierID'], unique=False)
    op.create_index(op.f('IX_PurchaseOrder_Status_PODate'), 'PurchaseOrder', ['Status_s', 'PODate'], unique=False)
    op.create_index(op.f('IX_PurchaseOrder_Status'), 'PurchaseOrder', ['Status_s'], unique=False)
    op.create_index(op.f('IX_PurchaseOrder_PartID'), 'PurchaseOrder', ['PartID'], unique=False)
    op.create_index(op.f('IX_PurchaseOrder_PODate'), 'PurchaseOrder', ['PODate'], unique=False)
    op.alter_column('Part', 'PartName',
               existing_type=sa.String(length=200),
               type_=sa.NVARCHAR(length=255, collation='Turkish_CI_AS'),
               existing_nullable=False)
    op.alter_column('Machine', 'Location',
               existing_type=sa.String(length=200),
               type_=sa.NVARCHAR(length=255, collation='Turkish_CI_AS'),
               existing_nullable=True)
    op.alter_column('Machine', 'Name',
               existing_type=sa.String(length=200),
               type_=sa.NVARCHAR(length=255, collation='Turkish_CI_AS'),
               existing_nullable=False)
    # ### end Alembic commands ###
