"""Sprint3 WorkOrder rules

Revision ID: cf902dfa60d1
Revises: 3eddb2b087cc
Create Date: 2025-08-26 13:28:08.062699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf902dfa60d1'
down_revision: Union[str, Sequence[str], None] = '3eddb2b087cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('WorkOrder', 'TechnicianID',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('WorkOrder', 'TechnicianID',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
