"""autogen: UQ WO.RequestID + CK Part.CurrentStock>=0

Revision ID: d429807daded
Revises: 1b6cd5d07169
Create Date: 2025-08-26 10:50:36.300059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd429807daded'
down_revision: Union[str, Sequence[str], None] = '1b6cd5d07169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
