"""baseline create tables

Revision ID: fa1332d3b12a
Revises: 
Create Date: 2025-08-22 13:01:03.978503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa1332d3b12a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Machine',
    sa.Column('MachineID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Code', sa.String(length=50), nullable=False),
    sa.Column('Name', sa.String(length=200), nullable=False),
    sa.Column('Location', sa.String(length=200), nullable=True),
    sa.Column('CommissionDate', sa.Date(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('MachineID'),
    sa.UniqueConstraint('Code')
    )
    op.create_table('Part',
    sa.Column('PartID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PartCode', sa.String(length=50), nullable=False),
    sa.Column('PartName', sa.String(length=200), nullable=False),
    sa.Column('Unit', sa.String(length=10), nullable=False),
    sa.Column('MinStock', sa.Integer(), server_default='0', nullable=False),
    sa.Column('CurrentStock', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('PartID'),
    sa.UniqueConstraint('PartCode')
    )
    op.create_table('Supplier',
    sa.Column('SupplierID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=200), nullable=False),
    sa.Column('Phone', sa.String(length=20), nullable=True),
    sa.Column('Email', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('SupplierID')
    )
    op.create_table('Technician',
    sa.Column('TechnicianID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FullName', sa.String(length=100), nullable=False),
    sa.Column('SkillLevel', sa.SmallInteger(), nullable=True),
    sa.Column('Phone', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('TechnicianID')
    )
    op.create_table('MaintenanceRequest',
    sa.Column('RequestID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MachineID', sa.Integer(), nullable=False),
    sa.Column('OpenedAt', sa.DateTime(), server_default=sa.text('SYSDATETIME()'), nullable=False),
    sa.Column('OpenedBy', sa.String(length=100), nullable=True),
    sa.Column('Priority_s', sa.SmallInteger(), nullable=True),
    sa.Column('Status_s', sa.String(length=20), server_default='Open', nullable=False),
    sa.Column('Description_s', sa.String(length=1000), nullable=True),
    sa.CheckConstraint("Status_s in ('Open','InProgress','Closed')", name='CK_Request_Status'),
    sa.ForeignKeyConstraint(['MachineID'], ['Machine.MachineID'], ),
    sa.PrimaryKeyConstraint('RequestID')
    )
    op.create_table('PurchaseOrder',
    sa.Column('POID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SupplierID', sa.Integer(), nullable=False),
    sa.Column('PartID', sa.Integer(), nullable=False),
    sa.Column('Qty', sa.Integer(), nullable=False),
    sa.Column('UnitPrice', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('PODate', sa.Date(), server_default=sa.text('CAST(GETDATE() AS DATE)'), nullable=False),
    sa.Column('ETA', sa.Date(), nullable=True),
    sa.Column('Status_s', sa.String(length=20), server_default='Created', nullable=False),
    sa.CheckConstraint("Status_s in ('Created','Ordered','Received','Canceled')", name='CK_PO_Status'),
    sa.CheckConstraint('Qty > 0', name='CK_PO_Qty_Positive'),
    sa.ForeignKeyConstraint(['PartID'], ['Part.PartID'], ),
    sa.ForeignKeyConstraint(['SupplierID'], ['Supplier.SupplierID'], ),
    sa.PrimaryKeyConstraint('POID')
    )
    op.create_table('WorkOrder',
    sa.Column('WorkOrderID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('RequestID', sa.Integer(), nullable=False),
    sa.Column('TechnicianID', sa.Integer(), nullable=True),
    sa.Column('OpenedAt', sa.DateTime(), server_default=sa.text('SYSDATETIME()'), nullable=False),
    sa.Column('ClosedAt', sa.DateTime(), nullable=True),
    sa.Column('Notes', sa.String(length=1000), nullable=True),
    sa.Column('Status_s', sa.String(length=20), server_default='Open', nullable=False),
    sa.CheckConstraint("Status_s in ('Open','InProgress','Closed')", name='CK_WO_Status'),
    sa.ForeignKeyConstraint(['RequestID'], ['MaintenanceRequest.RequestID'], ),
    sa.ForeignKeyConstraint(['TechnicianID'], ['Technician.TechnicianID'], ),
    sa.PrimaryKeyConstraint('WorkOrderID')
    )
    op.create_table('WarehouseTxn',
    sa.Column('TxnID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PartID', sa.Integer(), nullable=False),
    sa.Column('TxnType', sa.String(length=3), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('TxnDate', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
    sa.Column('Reason', sa.String(length=100), nullable=True),
    sa.Column('WorkOrderID', sa.Integer(), nullable=True),
    sa.CheckConstraint("TxnType in ('IN','OUT')", name='CK_WTxn_Type'),
    sa.CheckConstraint('Quantity > 0', name='CK_WTxn_Qty_Positive'),
    sa.ForeignKeyConstraint(['PartID'], ['Part.PartID'], ),
    sa.ForeignKeyConstraint(['WorkOrderID'], ['WorkOrder.WorkOrderID'], ),
    sa.PrimaryKeyConstraint('TxnID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WarehouseTxn')
    op.drop_table('WorkOrder')
    op.drop_table('PurchaseOrder')
    op.drop_table('MaintenanceRequest')
    op.drop_table('Technician')
    op.drop_table('Supplier')
    op.drop_table('Part')
    op.drop_table('Machine')
    # ### end Alembic commands ###
